sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 123456
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5tNSecXW9M4CsmTff7db
    access-key-secret: vVJSOhTJOqUC75E38IeZwSg7p7vjEa
    bucket-name: sky-takeout-jackvictor